### ISSUE TITLE
node app.js -d在Windows下面运行出错

### ISSUE THREAD

**Issue by fyrestone** [XueSeason/renren-album#1]
(node:8868) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: PATHERR: Expected absolute path.
(node:8868) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by XueSeason** [comment]
首先确保你已经执行过登录操作后，才能下载。

如果你已经登录了，仍然出现这个问题，可能是我并没有考虑 windows 环境的特殊性。

由于本人身边没有 Windows 设备，所以不保证其兼容性，希望得到理解。

我也会在近期抽出时间完善下整个项目。

**Comment by fyrestone** [comment]
确实登录过才操作的。。我晚上再试试看

**Comment by fyrestone** [comment]
Windows下虚拟机装了个Ubuntu，用同样的node.js 7.9.0，成功下载！
