### ISSUE TITLE
下载的并非原图

### ISSUE THREAD

**Issue by fyrestone** [XueSeason/renren-album#2]
如题。

**Comment by XueSeason** [comment]
非常感谢，明天我会提交抓取原图的代码。

**Comment by XueSeason** [comment]
今天 review 了一下代码，发现只能获取到的压缩过后的最高分辨率的图片了。一般图片上传到人人网后，都会自动压缩。

**Comment by fyrestone** [comment]
这个是renren-album下载的：
![image](https://cloud.githubusercontent.com/assets/6308809/25038985/0f7bffa0-2134-11e7-9bd0-215f188975be.png)
这个是在相册点“全屏”后，另存的：
![image](https://cloud.githubusercontent.com/assets/6308809/25039019/2cd4465c-2134-11e7-9e29-6d3de3befaef.png)

**Comment by XueSeason** [comment]
谢谢非常用心的案例，代码已经更新，下载的图片均为原图。
