### ISSUE TITLE
有些没有原图的会导致下载404

### ISSUE THREAD

**Issue by fyrestone** [XueSeason/renren-album#4]
![image](https://cloud.githubusercontent.com/assets/6308809/25082857/efa7c340-2385-11e7-931b-145e829c3823.png)
![image](https://cloud.githubusercontent.com/assets/6308809/25082913/41364dda-2386-11e7-8146-be0ce7883c49.png)

**Comment by XueSeason** [comment]
代码已经修改，当不存在原图的情况下，默认下载压缩后的高清图。
